-- ==========================================
-- ShiftLink Core API - PostgreSQL Database Initialization Script
-- 작성목적: 로컬 환경 및 초기 DB 세팅을 자동화합니다.
-- ==========================================

-- 1. 논리적 스키마 분리 생성
-- 도메인별 관리를 위해 3개의 스키마(core, billing, gamification)를 생성합니다.
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS billing;
CREATE SCHEMA IF NOT EXISTS gamification;

-- ==========================================
-- [공통 함수] updated_at 자동 갱신 트리거 함수 생성
-- MySQL과 달리 PostgreSQL은 ON UPDATE CURRENT_TIMESTAMP가 없으므로 함수로 전역 처리합니다.
-- ==========================================
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- 2. Schema: core (핵심 비즈니스, 정산 및 통합 운영)
-- ==========================================

-- [1.1 시스템 및 인프라 제어]
CREATE TABLE IF NOT EXISTS core.system_constants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 최신 PostgreSQL 권장 식별자 규격
    key_name VARCHAR(50) UNIQUE NOT NULL,       -- 키 이름 (예: MINIMUM_WAGE_2026)
    value VARCHAR(255) NOT NULL,                -- 적용 값 (예: 10030)
    description VARCHAR(255),                   -- 설명
    updated_at TIMESTAMP NOT NULL DEFAULT NOW() -- 변경일 (실시간 반영용)
);
-- 레코드가 UPDATE 될 때마다 updated_at을 자동으로 현재시간으로 변경해주는 트리거 적용
CREATE TRIGGER trg_system_constants_updated_at
BEFORE UPDATE ON core.system_constants
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TABLE IF NOT EXISTS core.app_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    os_type VARCHAR(20) NOT NULL CHECK (os_type IN ('AOS', 'IOS')), -- 모바일 운영체제 종류
    latest_version VARCHAR(20) NOT NULL,                            -- 스토어 최신 배포 버전
    min_required_version VARCHAR(20) NOT NULL,                        -- 이 버전 미만 사용자는 앱 강제 업데이트
    created_at TIMESTAMP NOT NULL DEFAULT NOW()                       -- 배포일시
);

-- [1.2 파일 마스터]
CREATE TABLE IF NOT EXISTS core.files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,                              -- 업로더 (시스템 에셋인 경우 NULL 허용)
    s3_url VARCHAR(500) NOT NULL,                -- 실제 파일이 저장된 S3 경로
    file_type VARCHAR(50) NOT NULL,              -- MIME 타입 (image/png 등)
    usage_context VARCHAR(50) NOT NULL,          -- 사용처 (AVATAR, RECEIPT 등 명확한 목적)
    is_deleted BOOLEAN DEFAULT FALSE,            -- 로컬 DB에서만 삭제 처리 (S3 물리적 삭제는 배치로 처리)
    created_at TIMESTAMP NOT NULL DEFAULT NOW()  -- 업로드 시간
);

-- [1.3 유저 및 권한 마스터]
CREATE TABLE IF NOT EXISTS core.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(50) UNIQUE,                                -- 앱 자체 접속 아이디 (소셜 가입자는 NULL)
    auth_provider VARCHAR(20) NOT NULL CHECK (auth_provider IN ('LOCAL', 'KAKAO', 'NAVER', 'GOOGLE')), -- 가입 채널
    provider_id VARCHAR(100),                                   -- 카카오/구글 등에서 전달받는 외부 회원 고유 해시 키
    password_hash VARCHAR(255),                                 -- 암호화된 비밀번호 (소셜 가입자는 NULL 허용하여 에러 방지)
    phone_number VARCHAR(20) UNIQUE,                            -- 핸드폰 번호 (무분별한 봇 가입 방지 및 명의 인증용)
    email VARCHAR(100),                                         -- 비밀번호 찾기 및 마케팅용 이메일
    name VARCHAR(50) NOT NULL,                                  -- 실명
    birth_date DATE,                                            -- 생년월일 (15세 미만 알바생 필터링 등 연령 확인용)
    nickname VARCHAR(50) NOT NULL,                              -- 서비스 내 표시될 닉네임
    role VARCHAR(20) NOT NULL CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN')), -- 권한 분리
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')), -- 계정 상태
    profile_image_id BIGINT REFERENCES core.files(id),          -- 프로필 사진 (files 테이블 참조)
    is_payday_warning_on BOOLEAN DEFAULT TRUE,                  -- 정산일 미수금 경고 알림 수신 여부 (별도 알림 테이블 통폐합)
    is_clockout_reminder_on BOOLEAN DEFAULT TRUE,               -- 퇴근 시간 리마인드 알림 수신 여부
    is_deleted BOOLEAN DEFAULT FALSE,                           -- 탈퇴 여부 (Soft Delete)
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),                -- 가입일시
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()                 -- 회원정보 최종 수정일시
);
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON core.users
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

-- [강력 최적화] 동일한 카카오 계정으로 두 번 가입 시 백엔드 단에서 충돌하기 전 DB 단에서 무결성 에러를 즉시 차단합니다.
CREATE UNIQUE INDEX idx_users_auth_provider_id ON core.users (auth_provider, provider_id) WHERE auth_provider != 'LOCAL';
-- 조회 최적화용 인덱스
CREATE INDEX idx_users_profile_image_id ON core.users (profile_image_id);
-- 논리적 삭제 조회를 위한 부분 인덱스(Partial Index). 활성 유저만 조회할 때 성능 극대화!
CREATE INDEX idx_users_is_deleted ON core.users (is_deleted) WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS core.login_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES core.users(id),          -- 접속한 유저
    client_type VARCHAR(20) NOT NULL CHECK (client_type IN ('WEB_PC', 'WEB_MO', 'APP_AOS', 'APP_IOS')), -- 로그인이 일어난 기기 환경
    user_agent VARCHAR(255) NOT NULL,                           -- 브라우저 및 디바이스 상세 정보
    login_ip VARCHAR(50) NOT NULL,                              -- 부정 접속 등을 추적할 수 있는 IP
    created_at TIMESTAMP NOT NULL DEFAULT NOW()                 -- 실제 접속 발생 시간
);
CREATE INDEX idx_login_histories_user_id ON core.login_histories (user_id);

CREATE TABLE IF NOT EXISTS core.user_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES core.users(id),
    device_token VARCHAR(255) UNIQUE NOT NULL,                  -- 무료 알림 수신용 푸시 토큰값
    os_type VARCHAR(20) NOT NULL CHECK (os_type IN ('AOS', 'IOS')), -- 토큰 전송 효율화를 위한 OS 구분
    last_login_at TIMESTAMP NOT NULL DEFAULT NOW()              -- 휴면 유저 마케팅 대상 선별용 최근 로그인 시간
);
CREATE INDEX idx_user_devices_user_id ON core.user_devices (user_id);

-- [1.4 운영 및 고객센터]
CREATE TABLE IF NOT EXISTS core.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES core.users(id),          -- 문의를 남긴 유저 ID
    category VARCHAR(50) NOT NULL CHECK (category IN ('BILLING', 'BUG', 'ACCOUNT')), -- 문의 카테고리 (결제, 버그, 계정 관련)
    title VARCHAR(255) NOT NULL,                                -- 문의 제목
    content TEXT NOT NULL,                                      -- 상세 내용
    evidence_image_id BIGINT REFERENCES core.files(id),         -- 오류 화면 증빙 캡처 (files 참조)
    status VARCHAR(20) NOT NULL CHECK (status IN ('WAITING', 'ANSWERED')), -- 답변 대기/완료 상태값
    answer_content TEXT,                                        -- 관리자가 작성한 답변 내용
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),                -- 문의 접수 일시
    answered_at TIMESTAMP                                       -- 답변 완료 일시
);
CREATE INDEX idx_inquiries_user_id ON core.inquiries (user_id);

-- [1.5 사업장 및 정산 정책]
CREATE TABLE IF NOT EXISTS core.workplaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES core.users(id),          -- 사업장을 소유/관리하는 유저
    name VARCHAR(100) NOT NULL,                                 -- 캘린더에 표시될 상호명
    theme_color VARCHAR(10) NOT NULL,                           -- 근무 캘린더에서 직관적 구분을 돕는 헥스코드 (예: #00704A)
    base_hourly_wage DECIMAL(10,2) NOT NULL,                    -- 기본 시급 (정산 오차 0%를 위해 DECIMAL 타입 고수!)
    payday INT NOT NULL CHECK (payday BETWEEN 1 AND 31),        -- 급여일 (1일 ~ 31일 제한)
    tax_rate_type VARCHAR(20) NOT NULL CHECK (tax_rate_type IN ('3.3', '4INSURANCE', 'NONE', 'CUSTOM')), -- 소득세 타입 (3.3%, 4대보험 등)
    custom_tax_amount DECIMAL(10,2),                            -- 고정 공제액이 있을 경우 수동 입력된 금액
    has_holiday_pay BOOLEAN DEFAULT FALSE,                      -- 주휴수당 자동 계산 활성화 여부
    has_overtime_pay BOOLEAN DEFAULT FALSE,                     -- 연장수당 (1.5배) 자동 계산 활성화 여부
    is_deleted BOOLEAN DEFAULT FALSE,                           -- 사업장 비활성화 (Soft Delete)
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_workplaces_updated_at
BEFORE UPDATE ON core.workplaces
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE INDEX idx_workplaces_user_id ON core.workplaces (user_id);
CREATE INDEX idx_workplaces_is_deleted ON core.workplaces (is_deleted) WHERE is_deleted = false;

-- [1.6 근태 데이터 (출퇴근, 사비 지출)]
CREATE TABLE IF NOT EXISTS core.work_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workplace_id BIGINT NOT NULL REFERENCES core.workplaces(id),-- 속한 사업장
    user_id BIGINT NOT NULL REFERENCES core.users(id),          -- 작성 유저
    client_type VARCHAR(20) NOT NULL CHECK (client_type IN ('WEB_PC', 'WEB_MO', 'APP_AOS', 'APP_IOS')), -- 데이터가 쓰여진 플랫폼 (오류 격리 추적용 핵심키)
    start_time TIMESTAMP NOT NULL,                              -- 출근 버튼 누른 일시
    end_time TIMESTAMP NOT NULL,                                -- 퇴근 버튼 누른 일시
    rest_minutes INT DEFAULT 30,                                -- 시스템 기본 휴게 시간 (분 단위, 유저가 수동 변경 가능)
    status VARCHAR(20) NOT NULL CHECK (status IN ('NORMAL', 'LATE', 'EARLY_LEAVE', 'SICK', 'SUBSTITUTE')), -- 지각/조퇴/정상 등 근태 상태
    total_calculated_wage DECIMAL(10,2) NOT NULL,               -- 이 날 번 일일 총급여 (조회 성능을 위한 캐싱 컬럼)
    memo TEXT,                                                  -- 업무 기록용 일기/메모
    receipt_image_id BIGINT REFERENCES core.files(id),          -- 법인카드 사용분 등 업무 영수증 제출용 이미지
    is_deleted BOOLEAN DEFAULT FALSE,                           -- 휴지통 (Soft Delete)
    created_at TIMESTAMP NOT NULL DEFAULT NOW()                 -- 레코드 등록일시
);
CREATE INDEX idx_work_logs_workplace_id ON core.work_logs (workplace_id);
CREATE INDEX idx_work_logs_user_id ON core.work_logs (user_id);
CREATE INDEX idx_work_logs_is_deleted ON core.work_logs (is_deleted) WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS core.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_log_id BIGINT NOT NULL REFERENCES core.work_logs(id),  -- 어느 출근 데이터(날짜)에 속하는 지출인지 종속됨
    client_type VARCHAR(20) NOT NULL CHECK (client_type IN ('WEB_PC', 'WEB_MO', 'APP_AOS', 'APP_IOS')), -- 등록 플랫폼 (버그 격리 확인)
    amount DECIMAL(10,2) NOT NULL,                              -- 지출액 (정산 테이블과의 오차를 막기위해 DECIMAL 통일)
    category VARCHAR(50) NOT NULL CHECK (category IN ('TRANSPORT', 'MEAL', 'ETC')), -- 카테고리
    description VARCHAR(255),                                   -- 상세 내역 설명
    expense_receipt_id BIGINT REFERENCES core.files(id),        -- 진짜 내 돈 주고 산 사비 증빙 영수증
    expensed_at TIMESTAMP NOT NULL,                             -- *실제 결제가 일어난 지출 일시 (며칠 뒤 등록해도 통계 일자가 꼬이지 않도록)*
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),                -- 시스템에 본 레코드가 생성된 일시
    is_deleted BOOLEAN DEFAULT FALSE
);
CREATE INDEX idx_expenses_work_log_id ON core.expenses (work_log_id);
CREATE INDEX idx_expenses_is_deleted ON core.expenses (is_deleted) WHERE is_deleted = false;

-- [1.7 대시보드 정산표 (가장 중요한 데이터 집계)]
CREATE TABLE IF NOT EXISTS core.period_settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workplace_id BIGINT NOT NULL REFERENCES core.workplaces(id),
    user_id BIGINT NOT NULL REFERENCES core.users(id),
    period_type VARCHAR(20) NOT NULL CHECK (period_type IN ('WEEKLY', 'MONTHLY')), -- 주급/월급 테이블을 통폐합 모델링함.
    -- 정규식을 이용한 엄격한 형식 유지 제약 조건 (예: 2026-W12 또는 2026-03)
    period_value VARCHAR(20) NOT NULL CHECK (period_value ~ '^\d{4}-(W\d{2}|\d{2})$'),
    total_work_hours DECIMAL(10,2) NOT NULL,                    -- 요약 대시보드에 뿌려질 총 누적 근무시간 캐시
    expected_wage DECIMAL(10,2) NOT NULL,                       -- 세금, 사비, 주휴수당 등 모두 적용된 '최종 예상 순수익'
    is_holiday_pay_met BOOLEAN DEFAULT FALSE,                   -- (주급 전용값) 이번주 주휴수당 발생 요건인 15시간을 달성했는지 여부 표시
    actual_deposit DECIMAL(10,2),                               -- 사장님이 실제로 내 통장에 이체하여, 내가 '입금 확인'버튼을 누른 실수령액
    status VARCHAR(20) NOT NULL CHECK (status IN ('WAITING', 'COMPLETED')) -- 미수금 대기 중 / 입금 완료 상태 관리
);
CREATE INDEX idx_period_settlements_workplace_id ON core.period_settlements (workplace_id);
CREATE INDEX idx_period_settlements_user_id ON core.period_settlements (user_id);


-- ==========================================
-- 3. Schema: billing (포인트 및 결제 시스템)
-- 코어 근태 도메인 장애 격리를 위해 스키마 분리
-- ==========================================
CREATE TABLE IF NOT EXISTS billing.point_wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES core.users(id),          -- 지갑 소유주
    point_type VARCHAR(20) NOT NULL CHECK (point_type IN ('FREE', 'PAID')), -- 이벤트 제공분(무료) vs 실 결제분(유료) 격리 보관
    original_amount INT NOT NULL,                               -- 최초 지급량
    remaining_amount INT NOT NULL,                              -- 잔여 포인트 (결제 및 사용 시 동기화)
    expires_at TIMESTAMP,                                       -- 무료 포인트 만료 일시 (유료 포인트는 무제한이므로 NULL)
    created_at TIMESTAMP NOT NULL DEFAULT NOW()                 -- 지갑 신규 발급일
);
CREATE INDEX idx_point_wallets_user_id ON billing.point_wallets (user_id);

CREATE TABLE IF NOT EXISTS billing.point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES core.users(id),
    point_wallet_id BIGINT NOT NULL REFERENCES billing.point_wallets(id), -- 어떤 지갑의 잔액이 변경되었는가
    transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('EARN', 'USE', 'EXPIRE', 'REFUND')), -- 변동 유형
    amount INT NOT NULL,                                        -- 양 (+, - 수치)
    description VARCHAR(255) NOT NULL,                          -- 사용 이력 설명 (예: "로그인 출석 보상", "아바타 옷 구매")
    created_at TIMESTAMP NOT NULL DEFAULT NOW()                 -- 발생일시
);
CREATE INDEX idx_point_transactions_wallet_id ON billing.point_transactions (point_wallet_id);


-- ==========================================
-- 4. Schema: gamification (락인 효과용 아바타 시스템)
-- 별도 확장 스케일링을 위해 스키마 분리
-- ==========================================
CREATE TABLE IF NOT EXISTS gamification.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,                                 -- 아이템 상표명
    category VARCHAR(50) NOT NULL CHECK (category IN ('HEAD', 'BODY', 'BACKGROUND')), -- 어느 파츠에 장착될 아이템인가
    price INT NOT NULL,                                         -- 지불해야 할 포인트
    asset_image_id BIGINT NOT NULL REFERENCES core.files(id),   -- 프론트에 렌더링될 아이템 이미지 (files 참조!)
    is_deleted BOOLEAN DEFAULT FALSE,                           -- 상점 노출 단종 여부
    created_at TIMESTAMP NOT NULL DEFAULT NOW()                 -- 출시일
);
CREATE INDEX idx_items_is_deleted ON gamification.items (is_deleted) WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS gamification.user_inventories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES core.users(id),
    item_id BIGINT NOT NULL REFERENCES gamification.items(id),  -- 소장한 아이템
    acquired_at TIMESTAMP NOT NULL DEFAULT NOW(),               -- 획득일
    UNIQUE(user_id, item_id)                                    -- 중복 구매/소장을 막기 위한 다중 제약
);

CREATE TABLE IF NOT EXISTS gamification.user_equipped_avatars (
    user_id BIGINT PRIMARY KEY REFERENCES core.users(id),       -- 1:1 매핑되어야 하므로 user_id를 바로 PK로 응용
    head_item_id BIGINT REFERENCES gamification.items(id),      -- 낀 머리아이템
    body_item_id BIGINT REFERENCES gamification.items(id),      -- 낀 옷
    bg_item_id BIGINT REFERENCES gamification.items(id),        -- 낀 배경장식
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()                 -- 옷 갈아입은 일시 (트리거 역할)
);
CREATE TRIGGER trg_user_equipped_avatars_updated_at
BEFORE UPDATE ON gamification.user_equipped_avatars
FOR EACH ROW EXECUTE FUNCTION update_timestamp();
